title: Museo di Zoologia di Bologna
description: Exploring and Integrating with ArCo ontologies. An ITS Project.
description2:[Home](https://eli-aga.github.io/project-AE/) [Methodology](https://eli-aga.github.io/project-AE/another-page.html) [Enrichment](https://eli-aga.github.io/project-AE/another-page3.html) [Discussion](https://eli-aga.github.io/project-AE/another-page2.html) 

navigation:
  - name: Home
    link: [https://eli-aga.github.io/project-AE/]
  - name: Methodogy
    link: /another-page.md
  - name: Enrichment
    link: /another-page3.md
  - name: Discussion
    link: /another-page2.md

show_downloads: false
google_analytics:
theme: jekyll-theme-merlot
